### ISSUE TITLE
postgres_exporter build failed

### ISSUE THREAD

**Issue by luowqn** [wrouesnel/postgres_exporter#171]
Today,I download this source code.
`go run mage.go releaseBin`

`2018/03/20 18:26:35 exec: git describe --dirty
2018/03/20 18:26:35 exec: git describe --abbrev=0
2018/03/20 18:26:35 exec: go list ./...
github.com/google/shlex
github.com/alecthomas/units
github.com/nicksnyder/go-i18n/i18n/language
github.com/nicksnyder/go-i18n/i18n/translation
github.com/pelletier/go-buffruneio
github.com/pelletier/go-toml
gopkg.in/yaml.v2
github.com/nicksnyder/go-i18n/i18n/bundle
github.com/nicksnyder/go-i18n/i18n
gopkg.in/alecthomas/kingpin.v3-unstable
github.com/alecthomas/gometalinter
Finished 1 of 6
golang.org/x/sys/unix
github.com/Bowery/prompt
github.com/kardianos/govendor/prompt
github.com/kardianos/govendor/cliprompt
github.com/dchest/safefile
github.com/kardianos/govendor/internal/pathos
github.com/kardianos/govendor/internal/vos
github.com/kardianos/govendor/internal/vfilepath
github.com/kardianos/govendor/pkgspec
github.com/kardianos/govendor/vcs
github.com/kardianos/govendor/vendorfile
github.com/pkg/errors
golang.org/x/tools/go/vcs
github.com/kardianos/govendor/context
github.com/kardianos/govendor/migrate
github.com/kardianos/govendor/help
github.com/kardianos/govendor/run
github.com/kardianos/govendor
Finished 2 of 6
golang.org/x/tools/cover
github.com/wadey/gocovmerge
Finished 3 of 6
github.com/mattn/goveralls
Finished 4 of 6
github.com/tmthrgd/go-bindata/internal/identifier
github.com/tmthrgd/go-bindata
github.com/tmthrgd/go-bindata/go-bindata
Finished 5 of 6
golang.org/x/tools/go/ast/astutil
golang.org/x/tools/go/buildutil
golang.org/x/tools/go/loader
github.com/GoASTScanner/gas
github.com/GoASTScanner/gas/output
github.com/nbutton23/zxcvbn-go/data
github.com/nbutton23/zxcvbn-go/adjacency
github.com/nbutton23/zxcvbn-go/match
github.com/nbutton23/zxcvbn-go/utils/math
github.com/nbutton23/zxcvbn-go/entropy
github.com/nbutton23/zxcvbn-go/frequency
github.com/nbutton23/zxcvbn-go/matching
github.com/nbutton23/zxcvbn-go/scoring
github.com/nbutton23/zxcvbn-go
github.com/GoASTScanner/gas/rules
github.com/kisielk/gotool
github.com/ryanuber/go-glob
github.com/GoASTScanner/gas/cmd/gas
Finished 6 of 6
golang.org/x/tools/cmd/gotype
Finished 1 of 25
github.com/tsenart/deadcode
Finished 2 of 25
golang.org/x/tools/go/types/typeutil
golang.org/x/tools/go/ssa
golang.org/x/tools/go/callgraph
golang.org/x/tools/go/ssa/ssautil
golang.org/x/tools/go/callgraph/cha
golang.org/x/tools/go/callgraph/rta
mvdan.cc/lint
mvdan.cc/unparam/check
# mvdan.cc/unparam/check
tools/src/mvdan.cc/unparam/check/check.go:141: undefined: types.SizesFor
running "go install -v mvdan.cc/unparam" failed with exit code 2
Finished 3 of 25
golang.org/x/text/transform
golang.org/x/text/width
github.com/mdempsky/unconvert
Finished 4 of 25
golang.org/x/tools/go/gcimporter15
golang.org/x/tools/go/gcexportdata
golang.org/x/lint
github.com/golang/lint/golint
Finished 5 of 25
Finished 6 of 25
github.com/gordonklaus/ineffassign
Finished 7 of 25
github.com/alexflint/go-scalar
github.com/alexflint/go-arg
github.com/walle/lll
github.com/walle/lll/cmd/lll
Finished 8 of 25
github.com/alexkohler/nakedret
Finished 9 of 25
github.com/opennota/check/cmd/structcheck
Finished 10 of 25
mvdan.cc/interfacer/check
mvdan.cc/interfacer
Finished 11 of 25
github.com/client9/misspell
github.com/client9/misspell/cmd/misspell
Finished 12 of 25
honnef.co/go/tools/ssa
honnef.co/go/tools/ssa/ssautil
honnef.co/go/tools/lint
honnef.co/go/tools/version
honnef.co/go/tools/lint/lintutil
honnef.co/go/tools/unused
honnef.co/go/tools/cmd/unused
Finished 13 of 25
github.com/dnephin/govet/internal/cfg
github.com/dnephin/govet/internal/whitelist
github.com/dnephin/govet
Finished 14 of 25
golang.org/x/tools/imports
golang.org/x/tools/cmd/goimports
Finished 15 of 25
github.com/opennota/check/cmd/varcheck
Finished 16 of 25
honnef.co/go/tools/deprecated
honnef.co/go/tools/callgraph
honnef.co/go/tools/callgraph/static
honnef.co/go/tools/staticcheck/vrp
honnef.co/go/tools/functions
honnef.co/go/tools/internal/sharedcheck
honnef.co/go/tools/staticcheck
honnef.co/go/tools/cmd/staticcheck
Finished 17 of 25
github.com/mibk/dupl/suffixtree
github.com/mibk/dupl/syntax
github.com/mibk/dupl/syntax/golang
github.com/mibk/dupl/job
github.com/mibk/dupl/printer
github.com/mibk/dupl
Finished 18 of 25
golang.org/x/tools/container/intsets
golang.org/x/tools/go/pointer
github.com/stripe/safesql
Finished 19 of 25
honnef.co/go/tools/simple
honnef.co/go/tools/cmd/megacheck
Finished 20 of 25
github.com/mdempsky/maligned
Finished 21 of 25
github.com/kisielk/errcheck/internal/errcheck
github.com/kisielk/errcheck
Finished 22 of 25
github.com/jgautheron/goconst
github.com/jgautheron/goconst/cmd/goconst
Finished 23 of 25
github.com/alecthomas/gocyclo
Finished 24 of 25
honnef.co/go/tools/cmd/gosimple
Finished 25 of 25
panic: parallel build failed

goroutine 15 [running]:
github.com/wrouesnel/postgres_exporter/vendor/github.com/magefile/mage/mg.runDeps(0x6d97a0, 0xc420010228, 0xc4200d3e78, 0x1, 0x1)
        /root/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/magefile/mage/mg/deps.go:103 +0x29e
github.com/wrouesnel/postgres_exporter/vendor/github.com/magefile/mage/mg.CtxDeps(0x6d97a0, 0xc420010228, 0xc420027678, 0x1, 0x1)
        /root/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/magefile/mage/mg/deps.go:66 +0x75
github.com/wrouesnel/postgres_exporter/vendor/github.com/magefile/mage/mg.Deps(0xc420027678, 0x1, 0x1)
        /root/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/magefile/mage/mg/deps.go:117 +0x57
main.makeBuilder.func1(0x5a7080, 0xc4203df920)
        /root/go/src/github.com/wrouesnel/postgres_exporter/magefile.go:608 +0xac
main.ReleaseBin.func1(0xc4203df920, 0xc4203df860, 0x5a7300, 0xc4200ccb00)
        /root/go/src/github.com/wrouesnel/postgres_exporter/magefile.go:686 +0x60
created by main.ReleaseBin
        /root/go/src/github.com/wrouesnel/postgres_exporter/magefile.go:689 +0x33a
exit status 2`
how to solve this question? @tmc @iterion @mjtrangoni @schnipseljagd @einhverfr

**Comment by wrouesnel** [comment]
I'm aware of this problem at the moment - the issue is some of the tools vendoring isn't correct. I'm working on a fix for the self contained build process - you can still build the binary via `go run mage.go binary`

**Comment by luowqn** [comment]
thank you !

**Comment by bondaj** [comment]
Hi, Its not buidling the binary. I tried it many times after the error. 

It was working on centos 7 sometime back. I am not sure what's causing the problem now.

[root@ip- postgres_exporter]# go run mage.go binary
2019/11/21 20:07:20 exec: git describe --dirty
2019/11/21 20:07:20 exec: git describe --abbrev=0
2019/11/21 20:07:20 exec: go list ./...
Building /root/go/src/github.com/wrouesnel/postgres_exporter/bin/postgres_exporter_v0.7.0_linux-amd64/postgres_exporter
# github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter
cmd/postgres_exporter/postgres_exporter.go:299:3: cannot use 0 (type int) as type bool in field value
cmd/postgres_exporter/postgres_exporter.go:299:3: too few values in composite literal
Error: running "go build -a -ldflags -extldflags '-static' -X main.Version=v0.7.0-9-g2772da8 -o /root/go/src/github.com/wrouesnel/postgres_exporter/bin/postgres_exporter_v0.7.0_linux-amd64/postgres_exporter ./cmd/postgres_exporter" failed with exit code 2
exit status 2
