### ISSUE TITLE
panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name

### ISSUE THREAD

**Issue by ipolishchuk** [wrouesnel/postgres_exporter#175]
Cannot start postgres_exporter

./postgres_exporter --version
postgres_exporter v0.4.5-1-g36e13ca (built with go1.10.1)

OS: CentOS 7.4, Postgres 10.3

Please advise. The full error is below. 

```# systemctl restart postgres_exporter-10
# tail -20f postgres_exporter-10.log
time="2018-04-10T14:35:55-04:00" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2018-04-10T14:35:55-04:00" level=info msg="Semantic Version Changed: 0.0.0 -> 10.3.0" source="postgres_exporter.go:925"
panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "pg_settings_shared_buffers_bytes", help: "Size of shared_buffers", constLabels: {}, variableLabels: []}

goroutine 1 [running]:
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc4200b8380, 0xc4201eea40, 0x1, 0x1)
        /home/ipolishchuk/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:354 +0x9e
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.MustRegister(0xc4201eea40, 0x1, 0x1)
        /home/ipolishchuk/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:153 +0x53
main.main()
        /home/ipolishchuk/go/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1129 +0x298```

**Comment by ipolishchuk** [comment]
Yesterday, on the same system, it complained about a different metric - pg_settings_checkpoint_segments. 
I've installed postgres_exporter on another identical system, it complains about it too:

panic: descriptors reported by collector have inconsistent label names or help strings for the same fully-qualified name, offender is Desc{fqName: "pg_settings_checkpoint_segments", help: "Number of checkpoint segments", constLabels: {}, variableLabels: []}
