### ISSUE TITLE
SIGSEGV and panic if postgres is down in version 0.4.7

### ISSUE THREAD

**Issue by sofianinho** [wrouesnel/postgres_exporter#245]
Hello,

I am using postgres exporter in version v0.4.7 with postgres version postgres:9.6-alpine (dockerhub docker image). The exporter I compiled  in a linux platform for amd64 architecture using this Dockerfile:

```Dockerfile
ARG pe_release=v0.4.7

FROM golang:1.11 as builder
ARG pe_release

LABEL name="Prometheus Postgres exporter"                            \
      description="Light Prometheus Postgres exporter image for use with postgres database"   \
      maintainer="github.com/sofianinho"


RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends --no-install-suggests git curl build-essential\
    && mkdir -p /go/src/github.com/wrouesnel/postgres_exporter \
    && git clone https://github.com/wrouesnel/postgres_exporter.git /go/src/github.com/wrouesnel/postgres_exporter\
    && cd /go/src/github.com/wrouesnel/postgres_exporter \
    && git checkout $pe_release \
    && go run mage.go -v binary

FROM  quay.io/prometheus/busybox:latest
ARG pe_release
ARG platform="linux-amd64"

LABEL name="Prometheus Postgres exporter"                            \
      description="Light Prometheus Postgres exporter image for use with postgres database"   \
      help1="run by placing your postgres config in DATA_SOURCE_NAME env variable, port 9187 is to be exposed" \
      help2="the complete command: docker run -d -p 9187:9187 --name postgres_exporter \
      -e DATA_SOURCE_NAME=\"postgresql://postgres:password@localhost:5432/postgres?sslmode=disable\" prometheus-postgres-exporter:latest"\
      maintainer="github.com/sofianinho"

ENV PE_RELEASE=$pe_release\
    PE_PLATFORM=$platform

COPY --from=builder  /go/src/github.com/wrouesnel/postgres_exporter/bin/postgres_exporter_${pe_release}_${platform}/postgres_exporter /bin/postgres_exporter


HEALTHCHECK --interval=15s --timeout=3s --start-period=5s --retries=5\
 CMD wget --quiet --tries=1 --spider -Y off http://localhost:9187 || exit 1

EXPOSE      9187
ENTRYPOINT  [ "/bin/postgres_exporter" ]

```
So this is what happens when everything is working (means that reports and metrics show up in Prometheus server), and then you stop the postgres database in an attempt to simulate a downtime.

```terminal
time="2018-12-24T12:15:18Z" level=warning msg="Proceeding with outdated query maps, as the Postgres version could not be determined: Error scanning version string: dial tcp 172.17.0.3:5432: connect: no route to host" source="postgres_exporter.go:1081"
time="2018-12-24T12:15:21Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1041"
time="2018-12-24T12:15:21Z" level=info msg="Error while closing non-pinging DB connection: <nil>" source="postgres_exporter.go:1041"
time="2018-12-24T12:15:21Z" level=info msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@172.17.0.3:5432/postgres?sslmode=disable): dial tcp 172.17.0.3:5432: connect: no route to host" source="postgres_exporter.go:1070"
time="2018-12-24T12:15:21Z" level=info msg="Error opening connection to database (postgresql://postgres:PASSWORD_REMOVED@172.17.0.3:5432/postgres?sslmode=disable): sql: database is closed" source="postgres_exporter.go:1070"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4dc917]

goroutine 269014 [running]:
database/sql.(*DB).Close(0x0, 0x97ad00, 0xc00006c230)
	/usr/local/go/src/database/sql/sql.go:759 +0x37
main.(*Exporter).getDB(0xc000184100, 0xc000024011, 0x57, 0xbf005153421851cd, 0xd83d772d4ad3, 0xcdc360)
	/go/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1040 +0x175
main.(*Exporter).scrape(0xc000184100, 0xc0003d60c0)
	/go/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1058 +0xde
main.(*Exporter).Collect(0xc000184100, 0xc0003d60c0)
	/go/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:785 +0x3c
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc0000260e0, 0xc0003d60c0, 0x97d740, 0xc000184100)
	/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x61
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:381 +0x302
```

It seems as a race condition issue in this file: https://github.com/wrouesnel/postgres_exporter/blob/master/cmd/postgres_exporter/postgres_exporter.go#L1034

Any ideas ?

By the way, I am thinking on setting my exporter container in restart=always mode to avoid this in the meantime.

Thanks in advance for your help;

**Comment by regeda** [comment]
Hi! Could you check the problem using the master branch?

**Comment by jamesnetherton** [comment]
This still seems to be a problem on the master branch.

The behaviour I see when the target Postgres instance is down, is that any requests to `/metrics` hang for a long time and then eventually the exporter crashes with the nil pointer exception.

It's easily reproducible by testing with Kubernetes or Docker.

**Comment by wrouesnel** [comment]
Weird that this seems to originate in the Go SQL library. Should be simple enough to add an integration test for.

**Comment by regeda** [comment]
@jamesnetherton Could you print the stack trace with the panic using `master` branch?

**Comment by jamesnetherton** [comment]
Here's the stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78633a]
goroutine 13 [running]:
database/sql.(*DB).conn(0x0, 0x97ec80, 0xc0000a01b8, 0x4bf401, 0xc000124040, 0x9, 0x7fa624404c58)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/database/sql/sql.go:1081 +0x3a
database/sql.(*DB).query(0x0, 0x97ec80, 0xc0000a01b8, 0xc0003f6030, 0x29, 0x0, 0x0, 0x0, 0x1, 0x8e3940, ...)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/database/sql/sql.go:1512 +0x66
database/sql.(*DB).QueryContext(0x0, 0x97ec80, 0xc0000a01b8, 0xc0003f6030, 0x29, 0x0, 0x0, 0x0, 0x29, 0xc0003f6030, ...)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/database/sql/sql.go:1494 +0xd3
database/sql.(*DB).Query(0x0, 0xc0003f6030, 0x29, 0x0, 0x0, 0x0, 0x29, 0x203000, 0x203000)
	/home/travis/.gimme/versions/go1.11.linux.amd64/src/database/sql/sql.go:1508 +0x82
main.queryNamespaceMapping(0xc0003f4780, 0xc000120b80, 0x902446, 0x1a, 0xc0001c3140, 0x2, 0x2, 0xc00020b5c0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1076 +0x1525
main.queryNamespaceMappings(0xc0003f4780, 0xc000120b80, 0xc000245e28)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1162 +0x2c7
main.(*Server).Scrape(0xc000120b80, 0xc0003f4780, 0x9827c0, 0xc0000c27c0, 0xc000474000)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:822 +0x85
main.(*Exporter).scrape(0xc000172090, 0xc0003f4780)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1276 +0x3dd
main.(*Exporter).Collect(0xc000172090, 0xc0003f4780)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1040 +0x3c
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc000411490, 0xc0003f4780, 0x97c580, 0xc000172090)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x61
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:381 +0x302
```

**Comment by regeda** [comment]
@jamesnetherton could you run the newest version on your environment?

**Comment by jamesnetherton** [comment]
SIGSEGV no longer occurs. Thanks!

**Comment by regeda** [comment]
Great!

**Comment by meyskens** [comment]
We've been having this issue too but we use the official Docker image where this patch isn't yet released to. Could it be possible to release a new version with this patch? Thank you!

**Comment by regeda** [comment]
You can use the “latest” tag while it’s not released a stable version.

**Comment by ntavares** [comment]
Hi @regeda it's been a few months, this is an important fix, IMO. When can we expect you to release a new version?

**Comment by wrouesnel** [comment]
Guess I probably should get that done. I've been putting it off partly because we've got so many changes right now. I'll see if I can cut one tonight though.

**Comment by wrouesnel** [comment]
0.6.0 has been released, and the fix went in before then anyway so this should be resolved.
