### ISSUE TITLE
postgres 11.2 has is throwing `panic: Unknown unit for runtime variable: "B"`

### ISSUE THREAD

**Issue by rnachire** [wrouesnel/postgres_exporter#404]
Hi, 
we are running postgres with exporter as sidecar .. with 9.x version, everything looks fine.. 

but, issue seen with 11.x 

time="2020-06-05T17:00:04Z" level=info msg="Established new database connection." source="postgres_exporter.go:995"
time="2020-06-05T17:00:04Z" level=info msg="Semantic Version Changed: 0.0.0 -> 11.2.0" source="postgres_exporter.go:925"
panic: Unknown unit for runtime variable: "B"

goroutine 26 [running]:
main.(*pgSetting).metric(0xc4202e5e50, 0xc420091dd8, 0x5)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/pg_setting.go:69 +0x52b
main.querySettings(0xc420096720, 0xc4200d6fa0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/pg_setting.go:38 +0x215
main.(*Exporter).scrape(0xc42020a100, 0xc420096720)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:1048 +0x4a8
main.(*Exporter).Collect(0xc42020a100, 0xc420096720)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/cmd/postgres_exporter/postgres_exporter.go:767 +0x3c
github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4201a26b0, 0xc420096720, 0x92a4e0, 0xc42020a100)
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:383 +0x61
created by github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/travis/gopath/src/github.com/wrouesnel/postgres_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:381 +0x302

please check and let us know if any further input required

**Comment by Self-Perfection** [comment]
@rnachire what version do you use? I see similar crash with postgres 12.3 + postgres_exporter 0.4.6. My exporter is obviously outdated and I'd like to know if I have a chance with never versions.

**Comment by mfuhrmann** [comment]
I've tested with 12.5 on Ubuntu 18. Same problem.
I'm also using 0.4.6 because I use the [Puppet module version](https://github.com/gbloquel/puppet-postgres_exporter) of this exporter.

**Comment by sysadmind** [comment]
Unit parsing has been extended repeatedly since 0.4.x (B suffix, 4kB/64kB, 1kB/2kB units) and v0.19.0 made pg_settings parsing non-fatal (#1252). Please upgrade; closing as resolved.
